services:
  elk-dind:
    build:
        context: ./
        dockerfile: ./Dockerfile
    container_name: elk-dind
    ports:
      - "5601:5601"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    stdin_open: true
    tty: true